eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinitionLocator: INFO
server:
  port: 8081

##Product service route
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: user-service
        uri: lb://user-service
        predicates[0]: Path=/api/**
      routes[1]:
        id: subscription-service
        uri: lb://subscription-service
        predicates[0]: Path=/Order/**
      routes[2]:
        id: notification-service
        uri: lb://notification-service
        predicates[0]: Path=/**
      routes[3]:
        id: authorization-service
        uri: lb://authorization-service
        predicates[0]: Path=/**
##Inventory service route

# Actuator route
#spring.cloud.gateway.routes[3].id=actuator
#spring.cloud.gateway.routes[3].uri=lb://order-service
#spring.cloud.gateway.routes[3].predicates[0]=Path=/api/actuator/**