spring:
  application:
    name: subscription-service
  datasource:
    password: 061201
    username: postgres
    url: jdbc:postgresql://localhost:5432/UserManagementDB
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    stream:
      bindings:
        consumeNotification-out-0:
          destination: notification-topic
      kafka:
        binder:
          brokers: localhost:9092
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 0

token:
  signing:
    public-key: Key/publicKey.pem
